[package]
name = "aslan-wavereduce"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aslan-data = {path="../aslan-data"}
rand = "0.8.5"