name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: alpaca-api
        uses: actions/checkout@v3
        with:
          repository: Delanyo32/alpaca-api
          token: ${{ secrets.RUST_PROJECT_KEYS }}
          path: alpaca-api
      - 
        name: aslan-bootstrap
        uses: actions/checkout@v3
        with:
          repository: Delanyo32/aslan-bootstrap
          path: master
      - 
        name: aslan-data
        uses: actions/checkout@v3
        with:
          repository: Delanyo32/aslan-data
          path: master
      - 
        name: aslan-wavereduce
        uses: actions/checkout@v3
        with:
          repository: Delanyo32/aslan-wavereduce
          path: master
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/aslan-core:latest